name: quran_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  get: ^4.6.5
  cupertino_icons: ^1.0.2
  loading_animation_widget: ^1.2.0+4
  audioplayers: ^3.0.1
  shared_preferences: 2.0.18
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
    - family: Amiri
      fonts: 
        - asset: assets/fonts/Amiri-Bold.ttf
        - asset: assets/fonts/Amiri-Regular.ttf
  uses-material-design: true

